# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mopyx_sample/ui/mainwindow.ui',
# licensing of 'mopyx_sample/ui/mainwindow.ui' applies.
#
# Created: Thu Nov  1 22:04:14 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.first_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name_edit.setObjectName("first_name_edit")
        self.gridLayout.addWidget(self.first_name_edit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.last_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_edit.setObjectName("last_name_edit")
        self.gridLayout.addWidget(self.last_name_edit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.full_name_label = QtWidgets.QLabel(self.centralwidget)
        self.full_name_label.setObjectName("full_name_label")
        self.gridLayout.addWidget(self.full_name_label, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.items_table = QtWidgets.QTableWidget(self.centralwidget)
        self.items_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.items_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.items_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.items_table.setShowGrid(False)
        self.items_table.setObjectName("items_table")
        self.items_table.setColumnCount(0)
        self.items_table.setRowCount(0)
        self.items_table.horizontalHeader().setVisible(False)
        self.items_table.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.items_table, 2, 0, 1, 1)
        self.selected_items_label = QtWidgets.QLabel(self.centralwidget)
        self.selected_items_label.setObjectName("selected_items_label")
        self.gridLayout_2.addWidget(self.selected_items_label, 3, 0, 1, 2)
        self.item_button_add = QtWidgets.QPushButton(self.centralwidget)
        self.item_button_add.setObjectName("item_button_add")
        self.gridLayout_2.addWidget(self.item_button_add, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.item_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.item_name_edit.setObjectName("item_name_edit")
        self.gridLayout_2.addWidget(self.item_name_edit, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.item_button_move_up = QtWidgets.QPushButton(self.centralwidget)
        self.item_button_move_up.setObjectName("item_button_move_up")
        self.verticalLayout.addWidget(self.item_button_move_up)
        self.item_button_move_down = QtWidgets.QPushButton(self.centralwidget)
        self.item_button_move_down.setObjectName("item_button_move_down")
        self.verticalLayout.addWidget(self.item_button_move_down)
        self.item_button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.item_button_delete.setObjectName("item_button_delete")
        self.verticalLayout.addWidget(self.item_button_delete)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MoPyX Sample", None, -1))
        self.first_name_edit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "John", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Last Name", None, -1))
        self.last_name_edit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Doe", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Full Name", None, -1))
        self.full_name_label.setText(QtWidgets.QApplication.translate("MainWindow", "full_name_label", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "First Name", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Character", None, -1))
        self.selected_items_label.setText(QtWidgets.QApplication.translate("MainWindow", "selected_items_label", None, -1))
        self.item_button_add.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Items", None, -1))
        self.item_name_edit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "sword", None, -1))
        self.item_button_move_up.setText(QtWidgets.QApplication.translate("MainWindow", "Move Up", None, -1))
        self.item_button_move_down.setText(QtWidgets.QApplication.translate("MainWindow", "Move Down", None, -1))
        self.item_button_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))

